# Render Blueprint for Legal Intelligence Platform
# This file configures the deployment of the backend API service

services:
  # Backend API Service
  - type: web
    name: legal-intelligence-api
    env: python
    plan: starter
    region: oregon
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements-render.txt
      python -m spacy download en_core_web_sm
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
      - key: EURI_API_KEY
        value: test-key
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
      - key: PYTHONPATH
        value: /opt/render/project/src
